template: true   # required for local templates
valuesFilePath: ./values.yml

pipelines:
  {{ range $value := .Values.dashboards }}
  - name: test_{{ $value }}_{{ .Values.pipelineName }}
    steps:
      - name: p1_s1
        type: Bash
        execution:
          onExecute:
            - echo "testing"
  {{ end }}
