resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: mygithub
      path: kunal-mazumdar/pipelines-local-test-repo
      
  - name: myPropertyBag
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
      
  - name: myPropertyBag2
    type: PropertyBag
    configuration:
      commitSha: 2
      runID: 2

pipelines:
  - name: demo_manual
    steps:
      - name: manual_trigger
        type: Bash
        configuration:
          inputResources:
            - name: myRepo_d
        execution:
          onExecute:
            - printenv
            - echo "hi"
