template: true   # required for local templates
valuesFilePath: ./values.yml

pipelines:
{{ range .Values.services }}
{{- $serviceName := .name -}}
{{ range .envs }}
  - name: my_first_pipeline_{{ $serviceName }}_{{ . }}
    steps:
      - name: p1_s1_{{ $serviceName }}_{{ . }}
        type: Bash
        configuration:
        execution:
          onExecute:
            - echo "test"        
{{ end }}
{{ end }}
