template: true   # required for local templates
valuesFilePath: ./values.yml

pipelines:
  - name: my_first_pipeline
    steps:
      - name: p1_s1
        type: Bash
        execution:
          onExecute:
            - echo "testing"
