valuesFilePath: values.yml

pipelines:
  - name: PS1x1
    steps:
      - name: PS2x3
        type: Bash
        configuration:
          environmentVariables:
            version: {{ ternary 1 2 (or (hasPrefix "dev" "{{gitBranch}}") (hasPrefix "milestone" "{{gitBranch}}") ) }}
            {{ if or ( hasPrefix "dev" "{{gitBranch}}" ) ( hasPrefix "milestone" "{{gitBranch}}" ) }}
            check: "pass"
            {{ else }}
            check: "fail"
            {{ end }}
        execution:
          onExecute:
            - cd /tmp
            
