valuesFilePath: ./values.yml

include:
  template: jfrog/HelloWorld/1.0.0

pipelines:
  - name: my_additional_pipeline
    steps:
      - name: my_additional_step
        type: Bash
        execution:
          onExecute:
            - echo "test"