pipelines:
  - name: pipeline_one  
    steps:
      - name: step_1_prep_env
        type: Bash
          integrations:
            - name: test_int
        execution:
          onExecute:
            - echo "test"
