resources:
 - name: connecting_resource_node_test
   type: PropertyBag
   configuration:
     key1: value1
     key2: value2
 - name: resource_pipelines
   type: GitRepo
   configuration:
     gitProvider: github_neha
     path: neha-mishraa/pipelines
     files: 
       include: ^README.md$
     branches:
       include: ^{{gitBranch}}$
#      buildOn:
#        commit: true

pipelines:
  - name: testing1
    steps:
      - name: nodeTestStep
        type: Bash
        configuration:
          nodePool: u18dynamic
          outputResources: 
            - name: connecting_resource_node_test
#               trigger: false
          integrations:
            - name: github_neha
        execution:
          onExecute:
            - write_output 
            "test=value"

      - name: c7dynamic
        type: Bash
        configuration:
          nodePool: c7dynamic
          inputResources:
            - name: connecting_resource_node_test
        execution:
          onExecute:
            - printenv
            - docker images
            
      - name: u20dynamic
        type: Bash
        configuration:
          nodePool: u20dynamic
          inputResources:
            - name: connecting_resource_node_test
        execution:
          onExecute:
            - printenv
            - docker images

      - name: win_2019
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: connecting_resource_node_test
        execution:
          onExecute:
            - write-output "Hi"
            - docker images
