resources:
  
  - name: dev_trigger
    type: CronTrigger
    configuration:
      interval: '*/1 * * * *'

  - name: prod_trigger
    type: CronTrigger
    configuration:
      interval: '*/2 * * * *'

pipelines:
  - name: cron_sanity_pipeline
    steps:
      - name: cron_sanity_step
        type: Bash
        configuration:
          inputResources:
            - name: dev_trigger
            - name: prod_trigger
        execution:
          onExecute:
            - printenv
            - echo $res_dev_trigger_name
            - echo $res_dev_trigger_resourceId
            - echo $res_prod_trigger_name
            - echo $res_prod_trigger_resourceId