valuesFilePath: ./values.yml

include:
  template: local/template1/0.0.0

pipelines:
  - name: my_first_pipeline
    steps:
      - name: my_first_step
        type: Bash
        execution:
          onExecute:
            - echo "test"