resources:
  - name: R1
    type: GitRepo
    configuration:
      gitProvider: kunal_gh
      path: kunal-mazumdar/pipelines-local-test-repo
      branches:
        include: npm
  - name: R2
    type: BuildInfo
    configuration:
      sourceArtifactory: myArt

pipelines:
  - name: kunal_npm_pipe_1
    configuration:
      outputResources:
        - name: R2
    steps:
      - name: step_1
        type: NpmBuild
        configuration:
          inputResources:
            - name: R1
          integrations:
            - name: myArt
          sourceLocation: "npm"
          repositoryName: templates-npm-remote

      - name: step_2
        type: NpmPublish
        configuration:
          repositoryName: templates-npm-local
          autoPublishBuildInfo: true
          inputSteps:
            - name: step_1
          integrations:
            - name: myArt
