template: true
valuesFilePath: ./values.yml
resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: {{ .Values.sourceRepository }}
      branches:
        include: {{gitBranch}}

pipelines:
  - name: Ps_variable_resolved_6730
    steps:
      - name: Ps_variable_resolved_6730
        type: Bash
        configuration:
          environmentVariables:
            env1: {{gitBranch}}
            env2: {{ .Values.sourceRepository }}
        execution:
          onExecute:
            - echo {{gitBranch}}
            - echo {{ .Values.sourceRepository }}
            - cd /tmp
            
