resources:
  - name: ffm_test_repo1
    type: GitRepo
    configuration:
      gitProvider: kunal_gh
      path: kunal-mazumdar/pipelines-local-test-repo
      branches:
        include: build-info
      buildOn:
        commit: true
        pullRequestCreate: true
        pullRequestClose: false
      cancelPendingRunsOn:
        newCommit: false
        pullRequestUpdate: true

pipelines:
  - name: ffm_test1
    configuration:
      jfrogCliVersion: 2
      environmentVariables:
        readOnly: {}
      integrations:
        - name: art
    steps:
      - name: matrix
        type: Matrix        
        stepMode: Bash
        configuration:
          inputResources:
            - name: ffm_test_repo1
              trigger: true
          multiNode: true            
        stepletMultipliers:
          fastFail: true
          environmentVariables:
            - name: service_d
              isStepMatrix: "true"
        execution:
          onStart:
            - |
              echo "[INFO] Fake onStart"              
          onExecute:
            - |
              cd $res_ffm_test_repo1_resourcePath
              mkdir -p /tmp/dir
              touch /tmp/dir/test.txt
              tar -czvf service-d-0.0.1.tgz /tmp/dir              
              old_build_name=$JFROG_CLI_BUILD_NAME
              build_name=$JFROG_CLI_BUILD_NAME    
              if [[ $isStepMatrix ]]
              then
                echo "[INFO] This is a Matrix step thus we are assigning the service name to the build name, \ 
                and on PostMatrix step we will aggregate those services Published Builds into one Build-Info"
                build_name=$name
                # export JFROG_CLI_BUILD_NAME=$name                
              fi        
              jf rt upload service-d-0.0.1.tgz km-generic-local --build-name $build_name --build-number $JFROG_CLI_BUILD_NUMBER
          onSuccess:
            - |
              echo "[INFO] Set Helm Build Info"
              echo $JFROG_CLI_BUILD_NAME
              jf --version
              echo "[INFO] Collect Environment Variables to the Build-Info"
              jf rt bce $build_name $JFROG_CLI_BUILD_NUMBER              
              echo "[INFO] Collect Information from Git to the Build-Info"
              jf rt bag $build_name $JFROG_CLI_BUILD_NUMBER                            
              echo "[INFO] Publishing Build-Info for step "
              jf rt build-publish $build_name $JFROG_CLI_BUILD_NUMBER  