valuesFilePath: ./values.yml

resources:
  - name: infosec_docker_release_trigger
    type: PropertyBag
    configuration:
      TRIGGER_TEAMS_DOCKER_PIPELINES: 0

pipelines:

  # Infosec Pipeline
  - name: infosec_docker_release
    steps:
      - name: docker_build
        type: Bash
        execution:
          onExecute:
            - echo "Building base Docker image"
      
      - name: docker_publish
        type: Bash
        configuration:
          inputSteps:
            - name: docker_build
          outputResources:
            - name: infosec_docker_release_trigger
        execution:
          onExecute:
            - echo "Publishing base Docker image"

  # Teams Pipelines
  {{- range $team := .Values.teams }}
  {{- range $target := $team.targets }}
  - name: {{ $team.name }}_{{ $target.targetImageName }}_docker_release
    steps:
      - name: docker_build
        type: Bash
        configuration:
          inputResources:
            - name: infosec_docker_release_trigger        
        execution:
          onExecute:
            - echo "Building Docker image with selected language"

      - name: docker_publish
        type: Bash
        configuration:
          inputSteps:
            - name: docker_build
        execution:
          onExecute:
            - echo "Publishing new Docker image"
  {{- end }}
  {{- end }}