valuesFilePath: ./values.yml

pipelines:
  - name: ci_next_tasks_dev
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: dev_test_publish
        type: Bash
        configuration:
          # Dynamic templating of integrations per given task.
          integrations:
            # Static integrations every task will be needing due to running publish task at the end.
            - name: {{ .Values.tasksUtils.artIntegration }}
            - name: {{ .Values.tasksUtils.gitIntegration }}
            {{ $selectedTask := (get .Values.tasksMetadata (.Values.taskToTest | toString)) }}
            {{ range .Values.tasksMetadata.pipelinesTriggerStep.taskIntegrations }}
            - name: {{ . }}
            {{ end }}
            - name: "{{ $selectedTask }}"
        execution:
          onStart:
            - "{{ .Values.taskToTest }}"
            - "{{ get .Values.tasksMetadata (.Values.taskToTest | toString) }}"                        
            - "{{ get .Values.tasksMetadata "pipelinesTriggerStep" }}"            
            - "{{ get .Values.tasksMetadata ".Values.taskToTest" }}"
            - "{{ $taskToTest := .Values.taskToTest }}"
            - "{{ $taskToTest }}"
            - "{{ get .Values.tasksMetadata "$taskToTest" }}"
            # Dont remove because onStart must be array.
            - echo "Checking task's type for onStart."
            {{- if eq .Values.tasksMetadata.pipelinesTriggerStep.type "go" }}
            - echo "Found go task, setting it up."
            # Do I need the setup-go for the dev probably yes.
            - task: jfrog/setup-go@v0.0.3
              input:
                version: 1.19.5
            - export GOPROXY="https://${int_{{ .Values.tasksUtils.artIntegration }}_user}:${int_{{ .Values.tasksUtils.artIntegration }}_apikey}@entplus.jfrog.io/artifactory/api/go/pipe-go-tasks-virtual"
            - export GONOSUMDB="github.com/jfrog/*"
            {{- end }}
          onExecute:
            - echo "Checking task's type for onExecute."
