valuesFilePath: ./values.yml

{{ $branchName := "{{gitBranch}}" | replace "-" "." }}

pipelines:
  - name: ci_next_tasks_dev
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: dev_test_publish
        type: Bash
        configuration:
          # Dynamic templating of integrations per given task.
          integrations:
            # Static integrations every task will be needing due to running publish task at the end.
            - name: {{ .Values.tasksUtils.artIntegration }}
            - name: {{ .Values.tasksUtils.gitIntegration }}
            {{ $taskToTest := .Values.taskToTest }}
            {{ range $k, $v := .Values.tasksMetadata }}
            {{ if eq $k $taskToTest }}
            {{ range $v.taskIntegrations }}
            - name: {{ . }}
            {{ end }}
            {{ end }}
            {{ end }}
        execution:
          onStart:
            - echo "Branch name = $branchName"
            {{ range $k, $v := .Values.tasksMetadata }}
            - {{ $k }}
            {{ end }}
            - "---------------------------"
            {{ range $k, $v := .Values.tasksMetadata }}
            - task __ {{ $taskToTest }}
            - task __ string __ {{ ($taskToTest | toString) }}
            {{ if eq $k .Values.taskToTest }}
            {{ range $v.taskIntegrations }}
            - {{ . }}
            {{ end }}
            {{ end }}
            {{ end }}
            - "{{ .Values.taskToTest }}"
            - "{{ get .Values.tasksMetadata (.Values.taskToTest | toString) }}"                        
            - "{{ get .Values.tasksMetadata "pipelinesTriggerStep" }}"            
            - "{{ get .Values.tasksMetadata ".Values.taskToTest" }}"
            - "{{ $taskToTest := .Values.taskToTest }}"
            - "{{ $taskToTest }}"
            - "{{ get .Values.tasksMetadata "$taskToTest" }}"
          onExecute:
            - echo "Checking task's type for onExecute."
