pipelines:
  - name: pipeline_one  
    steps:
      - name: step_1_prep_env
        configuration:
          integrations:
            - name: test_int
            - name: test_int_2          
        type: Bash
        execution:
          onExecute:
            - echo "test"
