resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: mygithub
      path: {{ sourceRepository }}
      branches:
        include: {{ gitBranch }}

pipelines:
  - name: P1
    steps:
      - name: S1
        type: Bash
        configuration:
          environmentVariables:
            env1: {{ gitBranch }}
            env2: {{ sourceRepository }}
        execution:
          onExecute:
            - echo {{ $myDict := dict "name1" "value1" "name2" "value2" "name3" "value 3" }}
            - echo {{ get $myDict "name1" }}
            
