pipelines:
  - name: my_first_pipeline
    configuration:
      jfrogCliVersion: 2
      environmentVariables:
        readOnly:
          XRAY_ENABLED: "{{ ternary true false ( hasPrefix "master" "{{gitBranch}}" ) }}"
          MODIFIED_GIT_BRANCH: "{{ "{{gitBranch}}" | replace "/" "." | replace "-" "."  }}"
    steps:
      - name: my_first_step
        type: Bash
        execution:
          onExecute:
            - echo "test"
            - echo "{{ ternary "true" "false" ( hasPrefix "master" "{{gitBranch}}" ) }}"
            - configure_jfrog_cli --artifactory-url https://master.jfrog-pipelines.com/artifactory --user admin --apikey password --server-name test
            - jf c show
            - use_jfrog_cli test
