pipelines:
  - name: Ps_variable_resolved_6730
    steps:
      - name: Ps_variable_resolved_6730
        type: Bash
        configuration:
          environmentVariables:
            env: 1
        execution:
          onExecute:
            - echo {{ gitBranch }}
            - echo {{ sourceRepository }}
            
