resources:
  - name: BuildInfo_test1_Description_Ressource
    type: BuildInfo
    configuration:
      sourceArtifactory: JFrog_Artifactory
      buildName: test1_Description

  - name: test1_Description_Sources_Ressource
    type: GitRepo
    configuration:
      gitProvider: kunal_gh
      path: kunal-mazumdar/pipelines-local-test-repo
      branches:
        include: develop|release\/.*|master
  - name: BuildInfo_test2_Description_Ressource
    type: BuildInfo
    configuration:
      sourceArtifactory: JFrog_Artifactory
      buildName: test2_Description

  - name: test2_Description_Sources_Ressource
    type: GitRepo
    configuration:
      gitProvider: kunal_gh
      path: kunal-mazumdar/pipelines-local-test-repo
      branches:
        include: develop|release\/.*|master

pipelines:
  - name: test1_Description_Packaging
    configuration:
      environmentVariables:
        readOnly:
          JFROG_PIPELINES_RUN_STATE_DEBUG: "true"
      jfrogCliVersion: 2
      dependencyMode:
        waitOnParentSuccess: true
        waitOnParentComplete: true
        waitOnChildComplete: true
      retentionPolicy:
        maxAgeDays: 30
        minRuns: 2
      integrations:
        - name: JFrog_Artifactory

    steps:
      - name: Build_sources_from_github
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - echo Test
  - name: test2_Description_Packaging
    configuration:
      environmentVariables:
        readOnly:
          JFROG_PIPELINES_RUN_STATE_DEBUG: "true"
      jfrogCliVersion: 2
      dependencyMode:
        waitOnParentSuccess: true
        waitOnParentComplete: true
        waitOnChildComplete: true
      retentionPolicy:
        maxAgeDays: 30
        minRuns: 2
      integrations:
        - name: JFrog_Artifactory

    steps:
      - name: Build_sources_from_github
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - echo Test
