template:
  namespace: local
  name: template1
  version: 1.2.0
  development: true

pipelines:
  - name: template_pipeline_2
    steps:
      - name: template_step_2
        type: Bash
        execution:
          onExecute:
            - echo "test from template"