template:
  namespace: local
  name: template1
  version: 0.0.0

pipelines:
  - name: template_pipeline
    steps:
      - name: template_step
        type: Bash
        execution:
          onExecute:
            - echo "test from template"