valuesFilePath: values.yml

pipelines:
  - name: {{ .Values.metadata.pipelineName }}
    configuration:
      jfrogCliVersion: "2"
      environmentVariables:
        readOnly:
          timeUnit:
            values: ["year", "month", "day", "hour", "minute"]
            default: "month"
            description: The unit of the time interval. year, month, day, hour or minute are allowed values. Default month.
          timeInterval:
            default: 1
            description: The time interval to look back before deleting an artifact. Default 1.
          repos:
            default: "abc"
            description: A list of repositories to clean. This parameter is required.
          dryRun:
            default: "false"
            values: ["true", "false"]
            description: If this parameter is passed, artifacts will not actually be deleted. Default false.
          paceTimeMS:
            default: 100
            description: The number of milliseconds to delay between delete operations. Default 0.
      
      {{ if eq "true" "{{ .Values.controls.cron.enabled }}" }}
      inputResources:
        - name: {{ .Values.metadata.pipelineName }}_cron_trigger
      {{ end }}

    steps:
      - name: delete_artifacts
        type: Bash
        execution:
          onStart:
            - jf c add --artifactory-url ${int_jfrogTokenIntegration_url} --access-token ${int_jfrogTokenIntegration_accessToken}
            - jf config show
            - echo 'Validate inputs'
            - echo 'Validate repos names'
            - echo 'Fetch artifacts based on conditions from repos'
            - echo 'Loop over artifacts and call delete with paceTimeMS delay'
            - echo 'Log report'
            - echo 'Save report as downloadable artifact'
          onExecute:
            - printenv