template:
  namespace: company
  name: demoTemplate1
  version: 1.0.0
  development: true

pipelines:
  - name: P1
    steps:
      - name: S1
        type: Bash
        execution:
          onExecute:
            - cd /tmp
